//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.DbModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_List_Column
    {
        public int CLC_ID { get; set; }
        public string CLC_Column { get; set; }
        public string CLC_ColumnZH { get; set; }
        public string CLC_Status { get; set; }
        public string CLC_JoinTable { get; set; }
        public string CLC_JoinWhere { get; set; }
        public string CLC_JoinColumnID { get; set; }
        public string CLC_JoinColumnValue { get; set; }
        public int CLC_ColumnType { get; set; }
        public int CLT_ID { get; set; }
    }
}
