//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.DbModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_Tree_Column
    {
        public int CTC_ID { get; set; }
        public int CTT_ID { get; set; }
        public string CTC_Column { get; set; }
        public string CTC_Status { get; set; }
        public string CTC_Url { get; set; }
        public int CTC_ColumnType { get; set; }
    }
}
