//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.DbModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_AddEdit_Column
    {
        public int CAC_ID { get; set; }
        public int CAT_ID { get; set; }
        public string CAT_Column { get; set; }
        public string CAT_ColunmZH { get; set; }
        public string CAT_Status { get; set; }
        public string CAT_EditType { get; set; }
        public string CAT_ValidateRules { get; set; }
        public int CAT_ColumnOrderBy { get; set; }
    }
}
