//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.DbModule
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyProjectContainer : DbContext
    {
        public MyProjectContainer()
            : base("name=MyProjectContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Config_AddEdit_Column> Config_AddEdit_Column { get; set; }
        public DbSet<Config_AddEdit_Table> Config_AddEdit_Table { get; set; }
        public DbSet<Config_List_Column> Config_List_Column { get; set; }
        public DbSet<Config_List_Table> Config_List_Table { get; set; }
        public DbSet<Config_Tree_Column> Config_Tree_Column { get; set; }
        public DbSet<Config_Tree_Tale> Config_Tree_Tale { get; set; }
        public DbSet<Sys_Module_Info> Sys_Module_Info { get; set; }
    }
}
