//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.DbModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Module_Info
    {
        public int SMI_ID { get; set; }
        public string SMI_Code { get; set; }
        public string SMI_Title { get; set; }
        public string SMI_Status { get; set; }
        public string SMI_ParentID { get; set; }
        public string SMI_Url { get; set; }
    }
}
